/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAuditRouteImport } from './routes/_shell.audit'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDetectionRouteImport } from './routes/_shell.detection'
import { Route as ShellOutputRouteImport } from './routes/_shell.output'
import { Route as ShellPolicyRouteImport } from './routes/_shell.policy'
import { Route as ShellProtectRouteImport } from './routes/_shell.protect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAuditRoute = ShellAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDetectionRoute = ShellDetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOutputRoute = ShellOutputRouteImport.update({
  id: '/output',
  path: '/output',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPolicyRoute = ShellPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProtectRoute = ShellProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof ShellAuditRoute
  '/dashboard': typeof ShellDashboardRoute
  '/detection': typeof ShellDetectionRoute
  '/output': typeof ShellOutputRoute
  '/policy': typeof ShellPolicyRoute
  '/protect': typeof ShellProtectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof ShellAuditRoute
  '/dashboard': typeof ShellDashboardRoute
  '/detection': typeof ShellDetectionRoute
  '/output': typeof ShellOutputRoute
  '/policy': typeof ShellPolicyRoute
  '/protect': typeof ShellProtectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/audit': typeof ShellAuditRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/detection': typeof ShellDetectionRoute
  '/_shell/output': typeof ShellOutputRoute
  '/_shell/policy': typeof ShellPolicyRoute
  '/_shell/protect': typeof ShellProtectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/detection'
    | '/output'
    | '/policy'
    | '/protect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/detection'
    | '/output'
    | '/policy'
    | '/protect'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/audit'
    | '/_shell/dashboard'
    | '/_shell/detection'
    | '/_shell/output'
    | '/_shell/policy'
    | '/_shell/protect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/audit': {
      id: '/_shell/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ShellAuditRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/detection': {
      id: '/_shell/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof ShellDetectionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/output': {
      id: '/_shell/output'
      path: '/output'
      fullPath: '/output'
      preLoaderRoute: typeof ShellOutputRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/policy': {
      id: '/_shell/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof ShellPolicyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/protect': {
      id: '/_shell/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ShellProtectRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAuditRoute: typeof ShellAuditRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDetectionRoute: typeof ShellDetectionRoute
  ShellOutputRoute: typeof ShellOutputRoute
  ShellPolicyRoute: typeof ShellPolicyRoute
  ShellProtectRoute: typeof ShellProtectRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAuditRoute: ShellAuditRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDetectionRoute: ShellDetectionRoute,
  ShellOutputRoute: ShellOutputRoute,
  ShellPolicyRoute: ShellPolicyRoute,
  ShellProtectRoute: ShellProtectRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
